# Generated by Django 4.2.3 on 2023-07-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default='admin', max_length=255),
            preserve_default=False,
        ),
    ]
