# Generated by Django 4.2.3 on 2023-07-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_customuser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
