# Generated by Django 4.2.3 on 2023-07-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_customuser_gstin_alter_customuser_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(blank=True, default='desc', max_length=200),
            preserve_default=False,
        ),
    ]
