# Generated by Django 4.2.3 on 2023-08-15 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_remove_order_product_alter_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
    ]
